language: java
deploy:
  provider: releases
  api_key:
    secure: G5pjR4ZK3hjmGob0nXI0kob2nlljeVirSu31H5u505YifCybLEln34iY9JqptjE8Rl2ho861d62cBSxsPWzbuEn/bYAf8IzUoLABhRmAn4rJQPVodQM/LGwJL8o8T/oJGdth3zF/Pi0NHspkOfINysUS2R58LKDCDy/enM8wgEhplFusl7fCW31mo5Itz7SgMmDxuxyln2riKCUk48oOo6hUIvQSTQsAWVoBOjFBJd+cdyu9qoOVJofbVkS5g8JM2SQxYZN8MqkRSlkmWga60bryWMOp1gSKk5Ddv80AkB3rC/4yE5MCNWKbaWSbVMM9fL9p4p6iSa4E4n8m/etYYm0nx1q1UWAHVimPBeqXCN86kPF9VwOgx9xzzJCO1LNkkRqUsJVjhoudq21FOLbGApkKJw1UwAoOvBNSQBhr+ywCPyG2XQiU9KfU05NZFJuO0PzBz/1blMYkRq1BqWvzA+fVumOyTvQ8IfEzhWwEyN2W+9U1W9LVt6LbsBaju5aGc0nCMTnLU8szIpa5mG2lIlXW+sa0fT2FyHY/S9N+m1OM6Op5lg883NIFkFTkpOpMX9YEDVtirxOAS1lpA5GVwQGzjxdpUFLwRpLL+oaM28CuL8v1EeDFEGU1P9Ufz+2aGRhg2+aQiBLEQUL2TDMDG9MZd0vxUtEbvDLL3CFflto=
  file: build//libs/xld-deployed-artifact-steps-plugin-1.0.4.jar
  on:
    all_branches: true
    tags: true
notifications:
  hipchat:
    rooms:
      secure: pWD0N51IyMu90OXsw/K7f+CLudJ1BMZYD1iFjQatFIjHR5tecdx3q7B+Xiq8iPV39ekS1johw580elI3ylvx0aES/ZAzTxZ9Y0nSOhjdTkqugTAnmp8GKhP2fOsvNDPQ8j42BlraetrL5yjjv24OXgXVkg/Lo46e0o2juxiBEDjJBavYv1NUmzSE2raEjMJZA2yni2HeIvUU1hB5KP4oy8riSKsKvbbCN8xXQ6yI6Gr1G9VoEknEJRIjy4ye+O//NPhHsxjCC3CLwLghJZSVI7wCVoWQovpyQuLIVU3oADait/NZOTTJJDzb3FbRWk02p0ePpBYVwNNjhsAss37S8UGAuLSr5qU6ZjbCXNxdWlZKpEmfXly/eYe1Hpuvw9j3V3+SNZprpWpmFCcUCojqaKlcvwV8GfMT0owkfP0OkPuqYjQkaZiiRGMpg4EY34GiveFf49bivEBkdwpHMzLmlheFmcWbxLtsck/BfODG9Zuyua2ypfl8uw2FoTkGRJEx7TmResTj+VwBE6ocn2TPK4v0fa8o9IxlLnaJPM/OtS5+sGUanwAVfwqjatRu0M//OMaYIIhudIpbYURBHZdWy9+2G9KVuJUwbLGo82yJGmd73hlzkKa3Tfk/AjsuNogNDKvv4TjA3i1ViLz5D1AeyECe5Eaj5j/0JM2knHiGKB4=
